baseURL = "/"
languageCode = "en-us"
title = "xAIM"
summaryLength = "20"

[params]
# header
masters_link = "https://www.nytimes.com/games/wordle/index.html"

# hero
hero_title ="eXplainable Artificial Intelligence in Healthcare Management"
hero_sub_title ="An Interdisciplinary Master’s Program at the Intersection of AI and Health Care"

# about 
about_title ="About"

# team
team_title = "Project Team"

# news
news_title = "Latest News"

# partners
partners_title = "Partner Universities"
partners_sub_title = "The masters is coordinated by University of Pavia, and involves world-renown experts from leading explainable AI institutions in Europe"

# contact
contact_title ="Contact Us"
location = "Via San Felice 5, 27100 Pavia, Italy"
email = "info@xaim.eu"
phone_number = "/"

# newsletter
newsletter_title = "Our Newsletter"
newsletter_sub_title = "Every three months, we summarize the progress of our work in a short newsletter."
