baseURL = "/"
languageCode = "en-us"
title = "xAIM"
summaryLength = "20"

[params]
# header
masters_link = "https://www.nytimes.com/games/wordle/index.html"

# team
team_title = "Project Team"

# news
news_title = "Latest News"

# contact
contact_title ="Contact Us"
location = "Via San Felice 5, 27100 Pavia, Italy"
email = "info@xaim.eu"
phone_number = "/"

#social media
twitter = "https://twitter.com/"
facebook = "https://www.facebook.com/"
instagram = "https://instagram.com/"
linkedin = "https://www.linkedin.com/"
