baseURL = "https://xaim.eu"
languageCode = "en-us"
title = "xAIM"
summaryLength = "20"

[params]
# header
masters_link = "https://xaim.eu"

# team
team_title = "Project Team"

# news
news_title = "Latest News"

# contact
contact_title ="Contact Us"
location = "Via San Felice 5, 27100 Pavia, Italy"
email = "info@xaim.eu"
phone_number = "/"

#social media
twitter = ""
facebook = ""
instagram = ""
linkedin = "https://www.linkedin.com/company/xaim-project/"
