backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"  
public_folder: "/images/news_images"

collections:
  - name: "home-page" 
    label: "Home page"  
    folder: "content"  
    create: false   
    fields: 
      - { label: "Title", name: "hero_title", widget: "string" }
      - { label: "Hero title", name: "hero_title", widget: "string" }
      - { label: "Hero subtitle", name: "hero_subtitle", widget: "string" }
      - { label: "About section title", name: "about_title", widget: "string" }
      - { label: "About section text", name: "body", widget: "markdown" }
      - { label: "Partner Universities section title", name: "partner_title", widget: "string" }
      - { label: "Partner Universities section subtitle", name: "partner_subtitle", widget: "string" }

  - name: "news" 
    label: "News"  
    folder: "content/news"  
    slug: "{{year}}-{{month}}-{{slug}}"
    create: true  
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Thumbnail Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Layout", name: "type", widget: "hidden", default: "news_art"}
  
  - name: "faq" 
    label: "Frequently Asked Questions"  
    folder: "content/faq"  
    create: false   
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  
  - name: "project" 
    label: "Project"  
    folder: "content/project"  
    create: false   
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
  
  - name: "masters-programme" 
    label: "Masters Programme"  
    folder: "content/masters-programme"  
    create: false   
    fields: 
      - { label: "Title", name: "real_title", widget: "string" }
      

